language: ruby
sudo: required
cache: bundler
os:
  #- linux
  - osx
env:
  - USE_ATLAS=1       # This configuration installs ATLAS, builds and tests the nmatrix, nmatrix-atlas, and nmatrix-lapacke gems
  - USE_OPENBLAS=1    # Installs OpenBLAS and reference LAPACK, builds and tests nmatrix, nmatrix-lapacke
  - USE_REF=1         # Installs OpenBLAS and reference LAPACK, builds and tests nmatrix, nmatrix-lapacke
  - NO_EXTERNAL_LIB=1 # No external libraries installed, only nmatrix
rvm:
  # The specific versions with clang specified are for Mac. The versions without
  # -clang are for linux systems. In the matrix, make sure to exclude each non-clang
  # osx combination.
  - 2.0
  - 2.1
  - 2.1.10-clang
  - 2.2
  - 2.2.7-clang
  - 2.3
  - 2.3.4-clang
  - 2.4
  - 2.4.1-clang
  - ruby-head
  - ruby-head-clang
  # JRuby versions --- experimental, pending merging Prasun's GSoC project.
  - jruby-9.0.5.0 # earliest supported version (uncomment when jruby-head is passing)
  - jruby-head    # latest supported JRuby
  # Make sure to add exclude lines for new JRuby versions below.

before_install: ./travis.sh before_install

install: ./travis.sh install

script: ./travis.sh script

# Define extra configurations to add to the build matrix.
# The idea here is that the USE_ATLAS=1 option should exercise all the ruby
# code, so it is the only one we need to test with all versions of ruby.
# For other configurations we only test with one version of ruby.
matrix:
  exclude:
    - rvm: jruby-head
      env: USE_ATLAS=1
    - rvm: jruby-head
      env: USE_OPENBLAS=1
    - rvm: jruby-head
      env: USE_REF=1
    - rvm: jruby-9.0.5.0
      env: USE_ATLAS=1
    - rvm: jruby-9.0.5.0
      env: USE_OPENBLAS=1
    - rvm: jruby-9.0.5.0
      env: USE_REF=1    
    # NOTE: The following ruby versions on OSX are currently unavailable
    # NOTE: See list: http://rubies.travis-ci.org/
    - os: osx
      rvm: 2.0
    # NOTE: The following ruby versions are GCC are we don't want to do
    #       these ones with osx, which has clang.
    - os: osx
      rvm: 2.1
    - os: osx
      rvm: 2.2
    - os: osx
      rvm: 2.3
    - os: osx
      rvm: 2.4
    - os: osx
      rvm: 2.5
    # NOTE: The following ruby versions we need to explicitly override
    #       and use clang with.
    - rvm: 2.1.10-clang
    - rvm: 2.2.7-clang
    - rvm: 2.3.4-clang
    - rvm: 2.4.1-clang
    - rvm: ruby-head-clang
    # FIXME: The following configuration is unavailable because ATLAS should be built from source.
    #        We need homebrew formula for ATLAS and its bottle.
    - os: osx
      env: USE_ATLAS=1
    # FIXME: The following configuration takes too long time when installing homebrew/dupes/lapack.
    #        We need the bottle of lapack formula.
    - os: osx
      env: USE_REF=1
  include:
    # The latest stable and head versions of ruby built by clang on OSX
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: ruby-head-clang
      env:
        - ruby_version=2.5.0 USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: ruby-head-clang
      env:
        - ruby_version=2.5.0 NO_EXTERNAL_LIB=1 CC=clang CXX=clang++    
    # The latest version of Ruby 2.4.x built by clang on OSX    
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.4.1-clang
      env:
        - ruby_version=2.4.1 USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.4.1-clang
      env:
        - ruby_version=2.4.1 NO_EXTERNAL_LIB=1 CC=clang CXX=clang++
    # The latest version of Ruby 2.3.x built by clang on OSX
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.3.4-clang
      env:
        - ruby_version=2.3.4 USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.3.4-clang
      env:
        - ruby_version=2.3.4 NO_EXTERNAL_LIB=1 CC=clang CXX=clang++
    # The latest version of Ruby 2.2.x built by clang on OSX	
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.2.7-clang
      env:
        - ruby_version=2.2.7 USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.2.7-clang
      env:
        - ruby_version=2.2.7 NO_EXTERNAL_LIB=1 CC=clang CXX=clang++	
    # The latest version of Ruby 2.1.x built by clang on OSX
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.1.10-clang
      env:
        - ruby_version=2.1.10 USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      rvm: 2.1.10-clang
      env:
        - ruby_version=2.1.10 NO_EXTERNAL_LIB=1 CC=clang CXX=clang++
  allow_failures:
    # trunk    
    - rvm: ruby-head
    - os: osx
      compiler: clang
      rvm: 2.5
      env:
        - ruby_version=2.5.0-dev USE_OPENBLAS=1 CC=clang CXX=clang++
    - os: osx
      compiler: clang
      rvm: 2.5
      env:
        - ruby_version=2.5.0-dev NO_EXTERNAL_LIB=1 CC=clang CXX=clang++

notifications:
  irc: "chat.freenode.net#sciruby"
